package com.sun.corba.se.PortableActivationIDL;


/**
* com/sun/corba/se/PortableActivationIDL/IIOP_CLEAR_TEXT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/tester/jenkins/workspace/zulu8-build-macos-aarch64/zulu-src.zulu8-emb-one/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Monday, November 23, 2020 4:04:07 AM PST
*/

public interface IIOP_CLEAR_TEXT
{

  /** Possible values for endpointType argument on Server.getEndpoint()
      * If you change the value of this constant then update
      * core.EndPoint accordingly.  It has a duplicate definition
      * to avoid a compilation dependency.
      */
  public static final String value = "IIOP_CLEAR_TEXT";
}
